import {Blanket} from './blankets'

export const BLANKETS: Blanket[]=[
    {
    id: 1,
    pname: 'Baby Want Designs Baby Swaddle Blanket',
    price: '₱420',
    material: 'Swaddle/Headband Set',
    color: 'Dusty Rose',
    brand: 'Baby Want Designs',
    feature: 'Skin Friendly, Lightweight, Soft, Breathable',
    imageUrl: 'assets/blankets/blanket1.jpg',
},
{
    id: 2,
    pname: 'Adjustable Baby Swaddle Wrap Set',
    price: '₱456',
    material: 'Cotton',
    color: 'Chevron/Arrows/Dots',
    brand: 'Mama Cheetah',
    feature: 'Lightweight, Breathable',
    imageUrl: 'assets/blankets/blanket2.jpg',
},
{
    id: 3,
    pname: 'Donsonny Baby Blanket for Boys Girls Soft Minky',
    price: '₱250',
    material: 'Polyester',
    color: 'Color Dinosaurs',
    brand: 'Donsonny',
    feature: 'Reversible, Breathable',
    imageUrl: 'assets/blankets/blanket3.jpg',
},
{
    id: 4,
    pname: 'Bayceen Purple Floral Print Minky Baby Blanket',
    price: '₱290',
    material: 'Polyester',
    color: 'Pink',
    brand: 'WARMAPE',
    feature: 'Skin Friendly',
    imageUrl: 'assets/blankets/blanket4.jpg',
},
{
    id: 5,
    pname: 'Konssy Waffle Baby Nursery Blankets',
    price: '₱399',
    material: '50% cotton 50% bamboo',
    color: 'Oat',
    brand: 'Konssy',
    feature: 'Breathable',
    imageUrl: 'assets/blankets/blanket5.jpg',
},
{
    id: 6,
    pname: 'Pro Goleem Fleece Baby Blanket with Satin Trim',
    price: '₱178',
    material: 'Fleece',
    color: 'Purple',
    brand: 'Pro Goleem',
    feature: 'Furry Friendly',
    imageUrl: 'assets/blankets/blanket6.jpg',
},
{
    id: 7,
    pname: 'Muslin Swaddle Blankets Neutral Receiving Blanket ',
    price: '₱890',
    material: 'Cotton',
    color: 'Green White',
    brand: 'Upsimples',
    feature: 'Lightweight, Breathable',
    imageUrl: 'assets/blankets/blanket7.jpg',
},
{
    id: 8,
    pname: 'Elephant Security Blanket Soft Baby Lovey Unisex',
    price: '₱480',
    material: 'Cotton',
    color: 'Grey',
    brand: 'Pro Goleem',
    feature: 'Lightweight',
    imageUrl: 'assets/blankets/blanket8.jpg',
},
]