import {Bodysuit} from './bodysuits'

export const BODYSUITS: Bodysuit[]=[
    {
    id: 1,
    pname: 'The Peanutshell Newborn Layette Gift',
    price: '₱1,200',
    color: 'Assorted',
    material: 'Cotton',
    type: 'Snap',
    imageUrl:'assets/bodysuits/suit1.jpg',       
},
{
    id: 2,
    pname: 'Bodysuits Infant Toddler Ruffled Neckline',
    price: '₱450',
    color: 'White, Grey',
    material: 'Cotton',
    type: 'Snap',
    imageUrl:'assets/bodysuits/suit2.jpg',       
},
{
    id: 3,
    pname: 'Short Sleeve Variety Onesies Bodysuits',
    price: '₱360',
    color: 'Assorted',
    material: 'Cotton',
    type: 'Snap',
    imageUrl:'assets/bodysuits/suit3.jpg',       
},
{
    id: 4,
    pname: 'Little Christian Rib Romper and Pants',
    price: '₱430',
    color: 'Blue',
    material: 'Cotton',
    type: 'No Closure',
    imageUrl:'assets/bodysuits/suit4.jpg',       
},
{
    id: 5,
    pname: 'Summer Short Sleeve Bowtie Bodysuit',
    price: '₱520',
    color: 'Blue',
    material: 'Cotton',
    type: 'Button',
    imageUrl:'assets/bodysuits/suit5.jpg',       
},
{
    id: 6,
    pname: 'LITTLE JAMJAMS Ruffled Zippered One-Piece',
    price: '₱630',
    color: 'Green',
    material: '95% bamboo fiber, 5% spandex',
    type: 'Zipper',
    imageUrl:'assets/bodysuits/suit6.jpg',       
},
{
    id: 7,
    pname: 'Gerber Unisex-Baby 5 Pack Onesies',
    price: '₱730',
    color: 'Black',
    material: 'Cotton',
    type: 'On Closure',
    imageUrl:'assets/bodysuits/suit7.jpg',       
},
{
    id: 8,
    pname: 'ZOEREA Newborn Baby Boy Clothes',
    price: '₱500',
    color: 'Brown,White',
    material: 'Cotton',
    type: 'Button',
    imageUrl:'assets/bodysuits/suit8.jpg',       
},
]