import {Diaper} from './diapers'

export const DIAPERS: Diaper[]=[
    {
    id: 1,
    pname: 'Wegreeco Washable Reusable Baby Cloth',
    price: '₱569',
    brand: 'Wegreeco',
    color: 'Flower',
    type: 'Infant Diaper',
    material: 'Polyester',
    imageUrl:'assets/clothdiaper/diaper1.jpg',
},
{
    id: 2,
    pname: 'Gerber Birdseye 3-Ply Prefold Cloth Diapers',
    price: '₱389',
    brand: 'Gerber',
    color: 'White',
    type: 'Potty Training Underwear',
    material: 'Cotton',
    imageUrl:'assets/clothdiaper/diaper2.jpg',
},
{
    id: 3,
    pname: 'BaeBae Goods Adjustable Cloth Diapers',
    price: '₱655',
    brand: 'BaeBae Goods',
    color: 'Grey',
    type: 'Booster Pad',
    material: 'Polyester, Suede',
    imageUrl:'assets/clothdiaper/diaper3.jpg',
},
{
    id: 4,
    pname: 'Berry Mauve 4-Pack Cloth Pocket Diapers',
    price: '₱599',
    brand: 'Noras Nursery',
    color: 'Berry Mauve',
    type: 'Booster Pad',
    material: 'Polyester, Suede',
    imageUrl:'assets/clothdiaper/diaper4.jpg',
},
{
    id: 5,
    pname: 'Simple Being Reusable Baby Cloth Diapers',
    price: '₱499',
    brand: 'Simple Being',
    color: 'Dc Batman Classic',
    type: 'Potty training',
    material: 'Polyester, Suede',
    imageUrl:'assets/clothdiaper/diaper5.jpg',
},
{
    id: 6,
    pname: 'Mimorou 45 Pcs Flannel Cloth Baby Wipes',
    price: '₱1,399',
    brand: 'Mimorou',
    color: 'White',
    type: 'Wipes',
    material: 'Cotton',
    imageUrl:'assets/clothdiaper/diaper6.jpg',
},
{
    id: 7,
    pname: 'Bamboo Cloth Diaper Inserts',
    price: '₱399',
    brand: 'Noras Nursery',
    color: 'White',
    type: 'Booster Pad',
    material: 'Bamboo',
    imageUrl:'assets/clothdiaper/diaper7.jpg',
},
{
    id: 8,
    pname: 'Naturally Natures Cloth Diaper Inserts',
    price: '₱799',
    brand: 'Naturally Nature',
    color: 'Charcoal',
    type: 'Booster Pad',
    material: 'Microfiber',
    imageUrl:'assets/clothdiaper/diaper8.jpg',
},
]