import {Hat} from './hats'

export const HATS: Hat[]=[
    {
    id: 1,
    pname: 'Knot Beanie Hats Soft for Infant Baby',
    price: '₱569',
    type: 'Elastic closure',
    material: '100% Polyester',
    wash: 'Machine Wash',
    imageUrl:'assets/hats/hat1.jpg',
},
{
    id: 2,
    pname: 'Newborn Baby Hat Bear Ears Infant Caps',
    price: '₱475',
    type: 'Pull-On closure',
    material: 'Fabric',
    wash: 'Hand Wash Only',
    imageUrl:'assets/hats/hat2.jpg',
},
{
    id: 3,
    pname: 'Durio UPF 50+ Beach Baby Sun Hat',
    price: '₱275',
    type: 'Toggle closure',
    material: '100% Cotton',
    wash: 'Hand Wash/Machin Wash',
    imageUrl:'assets/hats/hat3.jpg',
},
{
    id: 4,
    pname: 'Hispeka Baby Beanie Hat with Cute Smiley Face',
    price: '₱500',
    type: 'Elastic closure',
    material: 'Soft Acrylic',
    wash: 'Machine Wash',
    imageUrl:'assets/hats/hat4.jpg',
},
{
    id: 5,
    pname: 'GAP Unisex Baby Soft Knit Garter Hat',
    price: '₱130',
    type: 'Pull-On closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/hats/hat5.jpg',
},
{
    id: 6,
    pname: 'Baby Turban with Bows for Baby Girls ',
    price: '₱780',
    type: 'Elastic closure',
    material: '100% Polyester',
    wash: 'Hand wash only',
    imageUrl:'assets/hats/hat6.jpg',
},
{
    id: 7,
    pname: 'Adjustable Wide Brim Sun Protection Hat',
    price: '₱380',
    type: 'Buckle closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/hats/hat7.jpg',
},
{
    id: 8,
    pname: 'Carhartt Unisex Signature Canvas Cap',
    price: '₱450',
    type: 'Hook and Loop closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/hats/hat8.jpg',
},
]