import {Jacket} from './jackets'

export const JACKETS: Jacket[]=[
    {
    id: 1,
    pname: 'Cartoon Fleece Hooded Jacket Coat',
    price: '₱545',
    type: 'Zipper closure',
    material: 'Polar fleece',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket1.jpg',
},
{
    id: 2,
    pname: 'The Childrens Place Baby Boys Denim Jacket',
    price: '₱580',
    type: 'Button closure',
    material: 'Denim',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket2.jpg',
},
{
    id: 3,
    pname: 'Niceclould Winter Coat Toddler',
    price: '₱589',
    type: 'Zipper closure',
    material: 'Silk, Cotton',
    wash: 'Hand Wash Only',
    imageUrl:'assets/jackets/jacket3.jpg',
},
{
    id: 4,
    pname: 'Hanes Boys Baby Full Zip Sweatshirt',
    price: '₱450',
    type: 'Zipper closure',
    material: '65% Cotton, 35% Polyester',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket4.jpg',
},
{
    id: 5,
    pname: 'Feidoog Cardigan Crochet Sweater',
    price: '₱700',
    type: 'Button closure',
    material: 'Cotton',
    wash: 'Hand Wash',
    imageUrl:'assets/jackets/jacket5.jpg',
},
{
    id: 6,
    pname: 'Pullover Dads Little Dude Sweatshirt',
    price: '₱299',
    type: 'Pull On closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket6.jpg',
},
{
    id: 7,
    pname: 'Flannel Plaid Jacket Long Sleeve',
    price: '₱399',
    type: 'Button closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket7.jpg',
},
{
    id: 8,
    pname: 'V VALANCH Toddler Fleece Jacket',
    price: '₱600',
    type: 'Zipper closure',
    material: 'Polyester, fleece lining',
    wash: 'Machine Wash',
    imageUrl:'assets/jackets/jacket8.jpg',
},

]