import {Mitten} from './mittens'

export const MITTENS: Mitten[]=[
    {
    id: 1,
    pname: 'HAPIU Baby No Scratch Mittens',
    price: '₱355',
    type: 'Snap Closure',
    material: 'Cotton',
    wash: 'Hand/Machine Wash',
    imageUrl:'assets/mittens/mitten1.jpg',
},
{
    id: 2,
    pname: 'Gerber Baby Girls 4-Pack Mittens',
    price: '₱289',
    type: 'Pull-on closure',
    material: '97% Cotton, 3% Spandex',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten2.jpg',
},
{
    id: 3,
    pname: 'Newborn Baby Mittens No Scratch Gloves',
    price: '₱450',
    type: 'Pull-on closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten3.jpg',
},
{
    id: 4,
    pname: 'F Flammi 2 Pairs Toddler Mittens',
    price: '₱570',
    type: 'Pull-on closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten4.jpg',
},
{
    id: 5,
    pname: 'RATIVE Newborn Baby Cotton Gloves',
    price: '₱599',
    type: 'Pull-on closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten5.jpg',
},
{
    id: 6,
    pname: 'Newborn Mittens Girl Infant No Scratch Mittens',
    price: '₱499',
    type: 'Pull-on closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten6.jpg',
},
{
    id: 7,
    pname: 'Baby Teething Mitten Panda Hand Teether',
    price: '₱559',
    type: 'Snap Closure',
    material: 'Silicone',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten7.jpg',
},
{
    id: 8,
    pname: 'Fleece Mittens Toddler Mittens with String',
    price: '₱159',
    type: 'Pull-on Closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/mittens/mitten8.jpg',
},
]