import {Pant} from './pants'

export const PANTS: Pant[]=[
    {
    id: 1,
    pname: 'Amazon Essentials Unisex Babies Pants',
    price: '₱450',
    type: 'Pull On closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant1.jpg',
},
{
    id: 2,
    pname: 'The Peanutshell Camo and Dinosaur Baby Pants',
    price: '₱890',
    type: 'Elastic closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant2.jpg',
},
{
    id: 3,
    pname: 'U·nikaka Toddler Baby Girl Pants',
    price: '₱790',
    type: 'Elastic closure',
    material: '100% Cotton',
    wash: 'Hand Wash & Dry Clean & Machine Wash',
    imageUrl:'assets/pants/pant3.jpg',
},
{
    id: 4,
    pname: 'HonestBaby Baby Organic Cotton Honest Pants',
    price: '₱589',
    type: 'Drawstring closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant4.jpg',
},
{
    id: 5,
    pname: 'Bear Baby Soft Cotton Spandex Pants',
    price: '₱650',
    type: 'Pull On closure',
    material: '95% Cotton 5% Spandex/ 57% Cott 38% Poly 5% Spandex',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant5.jpg',
},
{
    id: 6,
    pname: 'IjnUhb Baby Boys 2-Pack Pants',
    price: '₱700',
    type: 'Drawstring closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant6.jpg',
},
{
    id: 7,
    pname: '4-Pack Pants Embroidery Printing ',
    price: '₱750',
    type: 'Snap closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant7.jpg',
},
{
    id: 8,
    pname: 'Toddler Boys Stretch Skinny Chino Pants',
    price: '₱640',
    type: 'Snap closure',
    material: 'Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/pants/pant8.jpg',
},
]