import {Tshirt} from './tshirts'

export const TSHIRTS: Tshirt[]=[
    {
    id: 1,
    pname: 'Long-Sleeve Side-snap Mitten-Cuff Shirt',
    price: '₱690',
    type: 'Pull On closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt1.jpg',
},
{
    id: 2,
    pname: 'Flexy Soft Stretch Shirt, Expandable Shoulder',
    price: '₱780',
    type: 'Pull On closure',
    material: '60% Cotton, 37% Polyester, 3% Spandex',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt2.jpg',
},
{
    id: 3,
    pname: 'Babysoy Unisex-Baby Kimono Tee',
    price: '₱200',
    type: 'Snap closure',
    material: '50% Azlon from soy, 50% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt3.jpg',
},
{
    id: 4,
    pname: 'Burts Bees Baby Baby Boys T-Shirts',
    price: '₱700',
    type: 'Pull On closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt4.jpg',
},
{
    id: 5,
    pname: 'Big bro Little bro Shirts',
    price: '₱850',
    type: 'Pull On closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt5.jpg',
},
{
    id: 6,
    pname: 'Hanes Baby T-Shirt, Flexy Soft Stretch Shirt',
    price: '₱900',
    type: 'Pull On closure',
    material: '60% Cotton, 37% Polyester, 3% Spandex',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt6.jpg',
},
{
    id: 7,
    pname: 'Gerber Baby Girls 3-Pack Short Sleeve Tees',
    price: '₱960',
    type: 'Pull On closure',
    material: '100% cotton jersey; neckline: 97% cotton, 3% spandex rib',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt7.jpg',
},
{
    id: 8,
    pname: 'Boys Short-Sleeve Pocket Henley Tee Shirt',
    price: '₱1360',
    type: 'Button closure',
    material: '100% Cotton',
    wash: 'Machine Wash',
    imageUrl:'assets/shirts/shirt8.jpg',
},
]